name: CI - Pruebas de Integración

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Ejecutar pruebas con Maven
        run: mvn verify
        working-directory: registraduria

      - name: Publicar reporte JaCoCo
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: registraduria/target/site/jacoco/